// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epsxwhiapixfhjecrkip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwc3h3aGlhcGl4ZmhqZWNya2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODc4MTIsImV4cCI6MjA3Mzc2MzgxMn0.Szvzp2_47uBCddGULdQd8eVSPVmpEt_63OcKE9uf-1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});